version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - trivy --version

  pre_build:
    commands:
      - npm install --legacy-peer-deps || echo "Advertencia en la instalacion"

  build:
    commands:
      - # Imprime el resumen directo en la consola de AWS CodeBuild
      - trivy fs . --severity HIGH,CRITICAL || echo "Vulnerabilidades detectadas por Trivy"
      - wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -O html.tpl
      - trivy fs . --format template --template "@html.tpl" -o trivy-report.html || echo "Reporte HTML generado"
      
artifacts:
  files:
    - trivy-report.html
